+incdir+../include
../DESIGN/Risi_Edge_Detector.v
../DESIGN/uart_wrapper.v
../DESIGN/apb_slave.v
../DESIGN/uart_top.v
../DESIGN/uart_reg_bank.v
../DESIGN/tx_fifo.v
../DESIGN/rx_fifo.v
../DESIGN/uart_transmitter.v
../DESIGN/uart_receiver.v
../DESIGN/baud_rate_generator.v
./uvm_lib.svh
../TB/PARAMETER/parameter_pkg.sv
../TB/INTERFACE/apb_if.sv
../TB/INTERFACE/uart_if.sv
../TB/INTERFACE/interrupt_if.sv
../TB/APB_VIP/apb_vip_pkg.sv
../TB/UART_VIP/uart_vip_pkg.sv
../TB/UART_RAL/uart_ral_pkg.sv
../TB/ENV/env_cfg_pkg.sv
../TB/ENV/scoreboard_pkg.sv
../TB/ENV/env_pkg.sv
../TB/SEQUENCE/sequence_pkg.sv
../TB/SEQUENCE/virtual_sequence_pkg.sv
../TB/TEST/test_pkg.sv
./tb.sv
